#include QMK_KEYBOARD_H

bool get_permissive_hold(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(5,KC_TAB):
        case LT(2,KC_ENT):
        case LT(3,OSM(MOD_LSFT)):
        case LT(6,KC_BSPC):
            // Immediately select the hold action when another key is tapped.
            return true;
        default:
            // Do not select the hold action when another key is tapped.
            return false;
    }
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(LCTL_T(KC_ESC), KC_B, KC_L, KC_D, KC_C, KC_V, KC_J, KC_Y, KC_O, KC_U, KC_COMM, KC_NO, LT(5,KC_TAB), LSFT_T(KC_N), LGUI_T(KC_R), LALT_T(KC_T), LCTL_T(KC_S), KC_G, KC_P, RCTL_T(KC_H), LALT_T(KC_A), RGUI_T(KC_E), RSFT_T(KC_I), KC_UNDS, CW_TOGG, KC_X, KC_Q, KC_M, KC_W, KC_Z, KC_K, KC_F, KC_QUOT, KC_SCLN, KC_DOT, KC_NO, KC_NO, LT(6,KC_BSPC), LT(3,OSM(MOD_LSFT)), KC_SPC, LT(2,KC_ENT), KC_NO),
    [1] = LAYOUT_split_3x6_3(KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, LT(5,KC_MINS), KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, LSFT_T(KC_TAB), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_NO, LT(4,KC_BSPC), KC_SPC, KC_LSFT, LT(2,KC_ENT), KC_NO),
    [2] = LAYOUT_split_3x6_3(KC_TRNS, KC_QUOT, KC_LT, KC_GT, KC_DQUO, KC_PDOT, KC_CIRC, KC_DLR, KC_LBRC, KC_RBRC, KC_PERC, KC_TRNS, KC_TRNS, KC_EXLM, KC_PMNS, KC_PPLS, KC_PEQL, KC_HASH, KC_TILD, KC_COLN, KC_LPRN, KC_RPRN, KC_QUES, KC_TRNS, KC_TRNS, KC_BSLS, KC_PSLS, KC_PAST, KC_AMPR, KC_GRV, KC_NO, KC_PIPE, KC_LCBR, KC_RCBR, KC_AT, KC_TRNS, KC_TRNS, KC_ENT, KC_SPC, KC_TRNS, KC_NO, KC_TRNS),
    [3] = LAYOUT_split_3x6_3(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_CUT, KC_COPY, KC_UP, KC_PSTE, KC_UNDO, KC_CAPS, KC_TRNS, KC_LSFT, KC_LGUI, KC_LALT, KC_LCTL, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_AGIN, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INS, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS),
    [4] = LAYOUT_split_3x6_3(KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS),
    [5] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_NO, KC_LSFT, KC_LGUI, KC_LALT, KC_LCTL, TO(1), KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_TRNS, KC_TRNS, KC_DEL, KC_TRNS, KC_TRNS, KC_TRNS),
    [6] = LAYOUT_split_3x6_3(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PMNS, KC_P7, KC_P8, KC_P9, KC_PSLS, KC_NO, KC_TRNS, KC_LSFT, KC_LGUI, KC_LALT, KC_LCTL, KC_NO, KC_PPLS, KC_P4, KC_P5, KC_P6, KC_PEQL, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PAST, KC_P1, KC_P2, KC_P3, KC_PDOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_P0, KC_ENT, KC_TRNS)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)



