/*
Copyright 2019 @foostan
Copyright 2020 Drashna Jaelre <@drashna>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include QMK_KEYBOARD_H

bool get_permissive_hold(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(4,KC_BSPC):
	case LT(2,KC_ENT):
            // Immediately select the hold action when another key is tapped.
            return true;
        default:
            // Do not select the hold action when another key is tapped.
            return false;
    }
}

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3(LCTL_T(KC_ESC), KC_B, KC_L, KC_D, KC_C, KC_V, KC_J, KC_Y, KC_O, KC_U, KC_COMM, KC_PIPE, MO(3), LSFT_T(KC_N), LGUI_T(KC_R), LALT_T(KC_T), LCTL_T(KC_S), KC_G, KC_P, RCTL_T(KC_H), LALT_T(KC_A), RGUI_T(KC_E), RSFT_T(KC_I), KC_UNDS, KC_BSLS, KC_X, KC_Q, KC_M, KC_W, KC_Z, KC_K, KC_F, KC_QUOT, KC_SCLN, KC_DOT, KC_PSLS, LT(5,KC_TAB), KC_LSFT, LT(6,KC_BSPC), KC_SPC, LT(2,KC_ENT), KC_DEL),
    [1] = LAYOUT_split_3x6_3(KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_MINS, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, LT(5,KC_TAB), LT(4,KC_BSPC), KC_LSFT, KC_SPC, LT(2,KC_ENT), KC_ESC),
    [2] = LAYOUT_split_3x6_3(KC_GRV, KC_QUOT, KC_LT, KC_GT, KC_DQUO, KC_NO, KC_NO, KC_DLR, KC_LBRC, KC_RBRC, KC_PERC, KC_TRNS, KC_TRNS, KC_EXLM, KC_PMNS, KC_PPLS, KC_PEQL, KC_HASH, KC_PDOT, KC_COLN, KC_LPRN, KC_RPRN, KC_QUES, KC_TRNS, KC_TRNS, KC_CIRC, KC_PSLS, KC_PAST, KC_AMPR, KC_NO, KC_TILD, KC_PIPE, KC_LCBR, KC_RCBR, KC_AT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS),
    [3] = LAYOUT_split_3x6_3(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_CUT, KC_COPY, KC_UP, KC_PSTE, KC_NO, KC_CAPS, KC_TRNS, KC_LSFT, KC_LGUI, KC_LALT, KC_LCTL, KC_NO, KC_AGIN, KC_LEFT, KC_DOWN, KC_RGHT, KC_UNDO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INS, KC_HOME, KC_END, KC_PGUP, KC_PGDN, KC_ENT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [4] = LAYOUT_split_3x6_3(KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS),
    [5] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_F7, KC_F8, KC_F9, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(1), KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(7), KC_NO, KC_F1, KC_F2, KC_F3, KC_F10, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO),
    [6] = LAYOUT_split_3x6_3(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PMNS, KC_P7, KC_P8, KC_P9, KC_PSLS, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PPLS, KC_P4, KC_P5, KC_P6, KC_PDOT, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PAST, KC_P1, KC_P2, KC_P3, KC_PEQL, KC_NO, KC_NO, KC_NO, KC_NO, KC_P0, KC_ENT, KC_NO)
};

